name: 'Hello World'
description: 'Greet someone'
outputs:
    version: 
      description: "Get version"
      value: ${{ steps.get-version.outputs.version }}
  runs:
    using: "composite"
    steps: 
      - id: get-version
        run: echo "::set-output name=version::$(cat ./version)"
        shell: bash