name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies # step3 name
        if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
        run: |
          cd ./frontend/
          yarn 
      - name: Build static files
        run: |
          cd ./frontend/
          yarn build
      - 
        name: Push to DockerHub
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # push: true
          tags: zozk/nginx-proxy-mamager:latest
          # repository: zozk/nginx-proxy-mamager
          # tag_with_ref: true