name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build and test
      run: |
        cd ./frontend/
        npm install 
        npm run build
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile 
    - name: Push 
      uses: BitMOE/nginx-proxy-mamager@v1
      with: 
        name: hub.docker.com/zozk/nginx-proxy-mamager # docker image 的名字
        username: ${{ secrets.DOCKER_USERNAME }} # 用户名
        password: ${{ secrets.DOCKER_PASSWORD }} # 密码
        registry: hub.docker.com 
        dockerfile: ./docker/Dockerfile 