name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies # step3 name
        if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
        run: |
          cd ./frontend/
          npm install # 安装 node modules 相关依赖
      - name: Build static files
        run: |
          cd ./frontend/
          npm run build
      # - name: Build the Docker image
      #   run: docker build . --file ./docker/Dockerfile 
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Push to DockerHub
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # push: true
          tags: zozk/nginx-proxy-mamager:latest
          # repository: zozk/nginx-proxy-mamager
          # tag_with_ref: true