name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: step1
      run: echo "::set-output name=version::$(cat ./version)"
      shell: bash
  build_docker:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{needs.get_version.outputs.version}}
      shell: bash
