name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: vars
      run: echo "::set-output name=v::$(/bin/cat .version)"
      shell: bash
    - run: echo ${{needs.vars.outputs.v}}
      shell: bash
