name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - run: echo version ${{ steps.foo.outputs.version }} 
      shell: bash
