name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Version from version file
      id: vars
      run: |
        echo "::set-output name=v::$(cat .version)"
      shell: bash
    - name: Display version 
      run: echo ${{steps.vars.outputs.v}}
      shell: bash
